spring:
  data:
    cassandra:
      contact-points: host.docker.internal
      port: 9042
      keyspace-name: ulixes_keyspace
      local-datacenter: Ithaca_datacenter
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: audit-group
      enable-auto-commit: true
topic-to-consume-message: event-topic